### ISSUE TITLE
No reflectivity info in VTF

### ISSUE THREAD

**Issue by romario516** [koerismo/PBR-2-Source#7]
there's no reflectivity calculated for textures for brushes.
v2.0.2

**Comment by koerismo** [comment]
Hi! Reflectivity info is generated for brushes, but it is much less apparent due to the shader lacking support for phong. I could attempt to scale up the envmap reflections to account for this, but at the moment only very reflective surfaces will receive envmap reflections. For now, you can modify the envmap tint and mask-contrast parameters to increase the reflectiveness.

**Comment by romario516** [comment]
No no no, not the envmap but the reflectivity, that defines how much and with what color light would bounce from that brush with this texture. This info can be inside either VTF or inside VMT as a parameter $reflectivity.

**Comment by koerismo** [comment]
Ah, I see. I assumed srctools would handle that, but I guess not. Will patch in the next version!

**Comment by koerismo** [comment]
Implemented in v2.0.3-beta. Feel free to reopen if there's any bugs I missed!

**Comment by romario516** [comment]
Textures always end up having reflectivity values as 0.2 0.2 0.2
